-- Generated by scripts/hypr2lua.
-- Source: omarchy-batman-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgb(f4fd22)", "rgb(1b1d1e)", "rgb(1b1d1e)", "rgb(1b1d1e)", "rgb(f4fd22)" },
  angle = 25,
}
local inactiveBorderColor = {
  colors = { "rgb(8a8a8a)", "rgb(1b1d1e)", "rgb(1b1d1e)", "rgb(1b1d1e)", "rgb(8a8a8a)" },
  angle = 25,
}

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 3,
    gaps_in = 6,
    gaps_out = 12,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    dim_inactive = false,
    dim_strength = 0.25,
    inactive_opacity = 0.8,
    blur = {
      enabled = true,
      size = 4,
      passes = 3,
      noise = 0.08,
    },
    shadow = {
      enabled = false,
    },
  },
})

hl.window_rule({
  name = "windowrule-2",
  no_dim = true,
  opacity = "1.0 override 1.0 override",
  match = {
    class = "(^brave-youtube\\.com__-Default$)",
  },
})
hl.window_rule({
  name = "windowrule-3",
  no_dim = true,
  opacity = "1.0 override 1.0 override",
  match = {
    class = "(^brave-www\\.netflix\\.com__browse-Default$)",
  },
})
