background            #1b1d1e
foreground            #a7a8a3
selection_background  #4d504c
selection_foreground  #f0e04a
background_opacity 0.7
# black
background_blur 1
color0  #1b1d1e
color8  #505354

# red
color1  #e6dc44
color9  #fff78e

# green
color2  #c8be46
color10 #fff27d

# yellow
color3  #f4fd22
color11 #feed6c

# blue
color4  #737174
color12 #919495

# magenta
color5  #747271
color13 #9a9a9d

#cyan
color6  #62605f
color14 #a3a3a6

#white
color7  #c6c5bf
color15 #dadbd6

